### ISSUE TITLE
兄弟，请问一下KITTI的点云标注方式现在你知道了吗？最近需要用KITTI的点云数据遇到了很多困难，能否交流一下

### ISSUE THREAD

**Issue by Gubudeng** [coronax1016/label_kitti_point_cloud#1]

**Comment by Sherlock-hh** [comment]
兄弟你搞定了嘛我也想和你交流一下，首先第一步你把点云下载下来了嘛？有百度网盘的链接嘛？那玩意太大了下起来还老断，给我折磨的不要不要的？还有就是为啥要标注，kitti不是有label文件嘛？你俩为啥还要标注？你是打算跑啥算法？

**Comment by XuanAo1016** [comment]
> _No description provided._

你有什么问题么？要么你留个联系方式？

**Comment by XuanAo1016** [comment]
> 兄弟你搞定了嘛我也想和你交流一下，首先第一步你把点云下载下来了嘛？有百度网盘的链接嘛？那玩意太大了下起来还老断，给我折磨的不要不要的？还有就是为啥要标注，kitti不是有label文件嘛？你俩为啥还要标注？你是打算跑啥算法？

我就是直接从kitti官网wget的。国内的话确实会比较慢，你可以考虑弄个梯子。另外，标注以后可以节约每次training的时候映射的时间，并且inference的时候看效果也更直观。

**Comment by Sherlock-hh** [comment]
> > 兄弟你搞定了嘛我也想和你交流一下，首先第一步你把点云下载下来了嘛？有百度网盘的链接嘛？那玩意太大了下起来还老断，给我折磨的不要不要的？还有就是为啥要标注，kitti不是有label文件嘛？你俩为啥还要标注？你是打算跑啥算法？
> 
> 我就是直接从kitti官网wget的。国内的话确实会比较慢，你可以考虑弄个梯子。另外，标注以后可以节约每次training的时候映射的时间，并且inference的时候看效果也更直观。

谢谢回复！不过我不用这个数据集了，但是我还是好奇，这个工具是可以直接在点云上进行标注吗，标注的保存格式是啥样的呢？你或许有用过frustum-pointnet这个算法吗？

**Comment by XuanAo1016** [comment]
因为我的网络是直接读取二进制的las文件，所以这个输出是直接写到las的类别里面。当然如果有需要你可以自己修改成自己喜欢的格式。
frustum-pointnet主要是针对已经标定好的图像和激光雷达数据一起作用。我当前的数据标定的不太好，所以没有做。不过后面这个肯定是趋势，不论是图像+点云或者RGBD的数据。

**Comment by Sherlock-hh** [comment]
> 因为我的网络是直接读取二进制的las文件，所以这个输出是直接写到las的类别里面。当然如果有需要你可以自己修改成自己喜欢的格式。
> frustum-pointnet主要是针对已经标定好的图像和激光雷达数据一起作用。我当前的数据标定的不太好，所以没有做。不过后面这个肯定是趋势，不论是图像+点云或者RGBD的数据。

等于这个工具是直接输入没有标注过的点云？然后输出每个点的类别到las里面？
我主要是想用frustum-pointnet训练自己的数据，但是一直都找不到合适的3d点云标注工具。

**Comment by XuanAo1016** [comment]
> > 因为我的网络是直接读取二进制的las文件，所以这个输出是直接写到las的类别里面。当然如果有需要你可以自己修改成自己喜欢的格式。
> > frustum-pointnet主要是针对已经标定好的图像和激光雷达数据一起作用。我当前的数据标定的不太好，所以没有做。不过后面这个肯定是趋势，不论是图像+点云或者RGBD的数据。
> 
> 等于这个工具是直接输入没有标注过的点云？然后输出每个点的类别到las里面？
> 我主要是想用frustum-pointnet训练自己的数据，但是一直都找不到合适的3d点云标注工具。

https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor 很好用 你可以自己修改一下使用
